# Generated by Django 5.2.10 on 2026-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
