# Generated by Django 5.2.10 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
